services:
  javalin-template:
    image: local/javalin-template:latest
    env_file:
      - env_files/dev/service.env
      - env_files/dev/otel.env
    ports:
      - "10001-10002:10000"
    networks:
      - develop-network
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
      mode: replicated
      replicas: 2

networks:
  develop-network:
    external: true
    name: develop
